// ============================================================
// Seed Scenarios - Realtime Speak Coach
// ============================================================

import type { Scenario } from './api.js';

export const SEED_SCENARIOS: Scenario[] = [
  // ─── English ───────────────────────────────────────────────
  {
    id: 'en-shopping-01',
    title: 'Buying a Coffee',
    titleCn: '买咖啡',
    description: 'Order your favorite drink at a busy coffee shop.',
    descriptionCn: '在繁忙的咖啡店点一杯你最爱的饮品。',
    category: 'shopping',
    difficulty: 3,
    language: 'en',
    systemPrompt: `You are a friendly barista at a coffee shop. Speak naturally, use casual English. Adapt complexity to user level {{level}}. Keep responses under 3 sentences.`,
    openingLine: "Hey! Welcome to Bean & Brew. What can I get started for you today?",
  },
  {
    id: 'en-business-01',
    title: 'Project Status Meeting',
    titleCn: '项目进度会议',
    description: 'Report your project progress to your manager in a 1-on-1.',
    descriptionCn: '在1对1会议中向经理汇报项目进度。',
    category: 'meeting',
    difficulty: 5,
    language: 'en',
    systemPrompt: `You are a senior engineering manager. Ask follow-up questions about timeline, blockers, and resource needs. Use professional but approachable English. Adapt to user level {{level}}.`,
    openingLine: "Good morning! So, let's dive into your project update. How are things progressing on your end?",
  },
  {
    id: 'en-travel-01',
    title: 'Hotel Check-in',
    titleCn: '酒店入住',
    description: 'Check into your hotel, ask about amenities and local tips.',
    descriptionCn: '办理酒店入住，询问设施和当地推荐。',
    category: 'travel',
    difficulty: 3,
    language: 'en',
    systemPrompt: `You are a hotel front desk receptionist. Be helpful and warm. Mention room details, breakfast hours, wifi password. Adapt to user level {{level}}.`,
    openingLine: "Good evening! Welcome to The Grand Harbor Hotel. Do you have a reservation with us?",
  },
  {
    id: 'en-ielts-01',
    title: 'IELTS Part 2 - Describe a Place',
    titleCn: '雅思Part2 - 描述一个地方',
    description: 'Practice IELTS Speaking Part 2 with examiner feedback.',
    descriptionCn: '练习雅思口语Part2，获得考官反馈。',
    category: 'ielts_mock',
    difficulty: 6,
    language: 'en',
    systemPrompt: `You are an IELTS speaking examiner. Give the candidate a Part 2 cue card topic, allow 1 minute prep (simulated), then let them speak for 1-2 minutes. Ask 1-2 follow-up questions. Evaluate band descriptors internally. Adapt to level {{level}}.`,
    openingLine: "Welcome to the speaking test. I'm going to give you a topic. I'd like you to talk about a place you have visited that you found particularly interesting. You should say where it is, when you went there, what you did there, and explain why you found it interesting. Please begin.",
  },
  {
    id: 'en-daily-01',
    title: 'Weekend Plans',
    titleCn: '周末计划',
    description: 'Chat with a friend about what to do this weekend.',
    descriptionCn: '和朋友聊聊这个周末的安排。',
    category: 'daily',
    difficulty: 2,
    language: 'en',
    systemPrompt: `You are a casual friend. Chat naturally about weekend plans - movies, restaurants, sports, staying home. Use slang and contractions appropriate for level {{level}}.`,
    openingLine: "Hey! So what are you up to this weekend? I was thinking we could do something fun.",
  },

  // ─── Japanese ──────────────────────────────────────────────
  {
    id: 'ja-shopping-01',
    title: 'コンビニで買い物',
    titleCn: '在便利店购物',
    description: 'Buy items at a Japanese convenience store.',
    descriptionCn: '在日本便利店购物。',
    category: 'shopping',
    difficulty: 3,
    language: 'ja',
    systemPrompt: `あなたはコンビニの店員です。丁寧な日本語で対応してください。ユーザーのレベル{{level}}に合わせて語彙と文法の複雑さを調整してください。`,
    openingLine: 'いらっしゃいませ！何かお探しですか？',
  },
  {
    id: 'ja-business-01',
    title: '自己紹介（面接）',
    titleCn: '面试自我介绍',
    description: 'Practice your self-introduction for a Japanese job interview.',
    descriptionCn: '练习日语面试的自我介绍。',
    category: 'business',
    difficulty: 5,
    language: 'ja',
    systemPrompt: `あなたは日本企業の面接官です。敬語を使い、志望動機や強みについて質問してください。レベル{{level}}に応じて質問の難易度を調整してください。`,
    openingLine: 'それでは、面接を始めさせていただきます。まず、自己紹介をお願いいたします。',
  },
  {
    id: 'ja-travel-01',
    title: '道を尋ねる',
    titleCn: '问路',
    description: 'Ask for directions to a famous landmark in Tokyo.',
    descriptionCn: '在东京问路去一个著名景点。',
    category: 'travel',
    difficulty: 3,
    language: 'ja',
    systemPrompt: `あなたは親切な東京の住民です。道を聞かれたら、分かりやすく説明してください。レベル{{level}}に合わせてください。`,
    openingLine: 'あ、すみません、何かお困りですか？',
  },
  {
    id: 'ja-jsst-01',
    title: 'JSST模擬テスト',
    titleCn: 'JSST模拟测试',
    description: 'Simulate a JSST speaking test with examiner.',
    descriptionCn: '模拟JSST日语口语考试。',
    category: 'jsst_mock',
    difficulty: 6,
    language: 'ja',
    systemPrompt: `あなたはJSST試験の面接官です。段階的に質問を出し、受験者の応答力を評価してください。レベル{{level}}に応じた質問をしてください。`,
    openingLine: 'JSSTの模擬テストを始めます。最初の質問です。あなたの趣味について教えてください。',
  },
  {
    id: 'ja-daily-01',
    title: '天気の話',
    titleCn: '聊天气',
    description: 'Small talk about weather with a neighbor.',
    descriptionCn: '和邻居闲聊天气。',
    category: 'daily',
    difficulty: 2,
    language: 'ja',
    systemPrompt: `あなたは隣人です。天気について気軽に話してください。レベル{{level}}に合わせた自然な日本語を使ってください。`,
    openingLine: 'おはようございます！今日はいい天気ですね。',
  },
];
